Exit Module - ERC721
gnosis/zodiac-module-exit pull request #45
Opened 2021-10-21 18:27 UTC by carlosfebres

### Summary 
Module to exit in exchange of a ERC721 token

2021-10-21 19:13 UTC, auryn-macmillan requested changes
- [ ] calculate circulating supply, rather than using total supply
- [x] implement circulating supply in a separate contract
- [ ] use transferFrom() for transactions into the safe

2021-10-21 19:13 UTC, auryn-macmillan commented on packages/contracts/contracts/ExitERC721Module.sol
> +        // TODO: use safeTransferFrom or transferForm?
Given that we know it will be going to a safe, I think `transferFrom()` is fine.

2021-10-21 19:13 UTC, auryn-macmillan commented on packages/contracts/contracts/ExitERC721Module.sol
> +        return supply / collection.totalSupply();
We should calculate circulating supply in a similar way to how we calculate it for ERC20 tokens.
i.e. it should be defined by an external contract and we should provide a reference implementation that allows the DAO to exclude some addresses from the supply. So `circulatingSupply = totalSupply - excludedBalances`. In almost all cases, the DAO's balance should be excluded from circulating supply.

2021-11-01 07:26 UTC, carlosfebres commented
Hi @auryn-macmillan I just added the Circulating Supply for the ERC721 exit module, please take a look at it 🚀 

### Things to do: 
- [ ] Create an `ICirculatingSupply` interface with the `get()` function.
- [ ] Use the ERC-165 in Circulating Supply contracts for validations in exit module contracts.
- [ ] Add tests for ERC721 Exit module.
- [ ] Add tests for ERC721 Circulating Supply

2021-11-04 17:00 UTC, auryn-macmillan requested changes
All of the tests pass, but I there seems to be a whole bunch of unhanded errors like this.
![image](https://user-images.githubusercontent.com/8453294/140384865-25ab0a98-a802-4774-83d2-6f3de00af478.png)

2021-11-04 17:04 UTC, auryn-macmillan commented
@carlosfebres, have you tried it with any existing ERC721 tokens?
Wondering if we should do a live test somewhere?

2021-11-15 09:48 UTC, carlosfebres commented
@auryn-macmillan PR is ready for review 🚀

2021-11-15 16:30 UTC, auryn-macmillan approved these changes
Looks good to me. Awesome work @carlosfebres.
I'll add the changes to our audit queue.

2021-11-15 16:30 UTC, merged